Audio interface
GoliasVictor/jogo. pull request #10
Opened 2024-06-19 01:25 UTC by vitordsp

Interface de Áudio com Efeitos sonoros
- Step -> movimento de player
- Fire -> entidade de fogo
- Water -> entidade de água
- PushBlock -> empurra bloco
- Wall -> player bate na parede

2024-06-19 09:49 UTC, GoliasVictor requested changes
Vi que ainda era draft depois de comentar, mas agora ja foi, mas bem, antes de deixar como pronto, da merge ou rebase da main no audio interface para ficar atualizado. 
E adiciona no mapa principal algum tipo de som.

Alem disso, garante a possibilidade de conseguir colocar uma musica de fundo, pausar e parar ela, ou seja ser possivel duas musicas serem tocadas ao mesmo tempo, (dependendo de como algumas coisas funcionam isso é dificil tem que ver como funciona no raylib pra mutiplas musicas), mas isso é só um comentario não é muito nescessario.

2024-06-19 09:49 UTC, GoliasVictor commented on src/Jogo/Audio.cs
> +            throw new NotImplementedException();
Falta implementar essa função

2024-06-19 09:49 UTC, GoliasVictor commented on src/Jogo/Audio.cs
> +            throw new NotImplementedException();
Falta implementar essa função

2024-06-19 09:49 UTC, GoliasVictor commented on src/Jogo/Audio.cs
> +            throw new NotImplementedException();
O que seria update Music?

2024-06-19 09:49 UTC, GoliasVictor commented on src/Jogo/Audio.cs
> +        public void PlaySound(IAudio.SoundEffect soundEffect)
Detalhe: USa um switch case que fica mais legivel

2024-06-19 09:49 UTC, GoliasVictor commented on src/Jogo/IAudio.cs
> +        /// <param>If no valid (or implemented) sound is provided, plays step sound</param>
Adiciona para que se não dar erro ou não reproduzir nenhum som, ou imprimir algo no terminal

2024-06-22 12:56 UTC, vitordsp commented on src/Jogo/Audio.cs
> +            throw new NotImplementedException();
implementei aqui, vou adicionar a PR
mudei o método pra private tbm, n é necessário ver isso fora do escopo da classe

2024-06-22 12:56 UTC, vitordsp commented on src/Jogo/Audio.cs
> +            throw new NotImplementedException();
removi essa, já tem uma func bem simples que faz isso

2024-06-22 12:59 UTC, vitordsp commented on src/Jogo/Audio.cs
> +            throw new NotImplementedException();
implementei ela, já altero na PR
Mas basicamente tem que chamar o UpdateMusic a todo ciclo do jogo para a música nao parar de tocar
Como parametro se colocar uma outra música ele vai atualizar a audioStream e trocar a musica que ta tocando

2024-06-22 12:59 UTC, vitordsp commented on src/Jogo/Audio.cs
> +        public void PlaySound(IAudio.SoundEffect soundEffect)
ok, vou atualizar

2024-06-22 12:59 UTC, vitordsp commented on src/Jogo/IAudio.cs
> +        /// <param>If no valid (or implemented) sound is provided, plays step sound</param>
n entendi
se n conseguir tocar, imprimir no terminal?
ok

2024-06-22 16:02 UTC, GoliasVictor commented on src/Jogo/IAudio.cs
> +        /// <param>If no valid (or implemented) sound is provided, plays step sound</param>
Se não conseguir tocar, imprimir no terminal que deu um erro ou coisa do tipo, é importante que os erros não possam passar despercebidos, deixando algum registro

2024-06-22 16:18 UTC, GoliasVictor requested changes
So arrumar o detalhe de que o audio  é um sistema, fora isso me parece tudo bem

2024-06-22 16:18 UTC, GoliasVictor commented on src/Jogo/Audio/IAudio.cs
Interface de audio é um `ISystem`,  que herda system, e adiciona alguns metodos a mais, então  o UpdateMusic, seria um Update apenas, ou seja, não precisaria estar aqui se herdasse de sistema, eu meio que errei de já não ter criado um arrya de inicialização de sistemas no começo

2024-06-22 16:43 UTC, vitordsp commented on src/Jogo/IAudio.cs
> +        /// <param>If no valid (or implemented) sound is provided, plays step sound</param>
a Raylib já imprime!

2024-06-22 19:37 UTC, GoliasVictor approved these changes
Me parece tudo certo :D

2024-06-22 19:41 UTC, merged