Components core
GoliasVictor/jogo. pull request #2
Opened 2024-06-14 15:44 UTC by GoliasVictor

2024-06-14 16:06 UTC, IsaelGabriel requested changes

2024-06-14 16:06 UTC, IsaelGabriel commented on src/Jogo/Program.cs
> +    private static IScene ActualScene;
Mudar nome da variável para ```CurrentScene```, 'actual' não equivale ao termo 'atual' em português.

2024-06-14 16:06 UTC, IsaelGabriel commented on src/Jogo/Models/IEntity.cs
> +	void Render(LevelScene level, int x, int y);
Não faz sentido o método Render carregar a posição do objeto sendo que é responsabilidade dele ter essa informação.

2024-06-18 01:26 UTC, vitordsp commented on src/Jogo/Models/TileVec2.cs
> +struct TileVec2 {
tem algum motivo pra isso aqui chama TileVec[2] ?

2024-06-18 01:32 UTC, vitordsp commented on src/Jogo/Scripts/PlayerMovingSystem.cs
> +class PlayerMovingSystem : ISystem<LevelScene>
N seria melhor PlayerMovementSystem?

2024-06-18 04:40 UTC, GoliasVictor commented on src/Jogo/Models/TileVec2.cs
> +struct TileVec2 {
Foi mudado para grid, mas é porque é um vetor de tamanho 2 na grid

2024-06-18 04:41 UTC, GoliasVictor commented on src/Jogo/Scripts/PlayerMovingSystem.cs
> +class PlayerMovingSystem : ISystem<LevelScene>
Meu ingles não é muito bom, vo mudar

2024-06-18 06:09 UTC, IsaelGabriel approved these changes

2024-06-18 13:33 UTC, vitordsp approved these changes
ta top

2024-06-18 14:34 UTC, merged